Hw03 frequency analysis
AGrishin63/griHW pull request #3
Opened 2020-04-02 18:59 UTC by AGrishin63

2020-04-12 16:30 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/79863/6027/

Здравствуйте!

Вы написали , что убрали все лишнее, но в итоге в PR теперь 3 ДЗ вместо одного, а старые замечания не исправлены.

Давайте сделаем так, чтобы в PR было только одно ДЗ. 
Скорее всего нужно подмержить в hw03_frequency_analysis мастер (не руками копировать-ставлять файлы с кодом).

Можете создать новый PR, если с этим тяжко.

Потом продолжим, спасибо!

2020-04-12 16:30 UTC, Antonboom commented on hw01_hello_now/main.go
> +	fmt.Println("current time:", time.Now().Format("2006-01-02 15:04:05 +0000 UTC"))
Как сюда попало 1 ДЗ?

2020-04-12 16:30 UTC, Antonboom commented on hw02_unpack_string/unpack.go
> +https://github.com/AGrishin63/griHW/compare/hw02_unpack_string?expand=1&template=hw02_unpack_string.md
Почему здесь 2 ДЗ?

И что за ссылка посреди кода - это не скомпилируется. Хотя бы комментарий

2020-04-12 16:30 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +// func main() {
Про неиспользуемый код я уже писал.

2020-04-14 14:59 UTC, AGrishin63 commented on hw01_hello_now/main.go
> +	fmt.Println("current time:", time.Now().Format("2006-01-02 15:04:05 +0000 UTC"))
Добрый день. В экземпляре на моём компьютере все замечания устранены. Я старался делать всё по инструкции, почему мой вариант не попал к вам и почему в PR 3 ДЗ я не знаю и не вижу трёх ДЗ. Кроме того я просил объяснить откуда надо отправлять преподавателю ссылки на PR? В инструкции сказано, что в личном кабинете OTUS есть ссылка на чат с преподавателем, я не нашёл этой ссылки. В личном кабинете OTUS в домашних заданиях 1 и 2 были ссылки, а в ДЗ 3 ссылок нет. Далее:"Скорее всего нужно подмержить в hw03_frequency_analysis мастер (не руками копировать-ставлять файлы с кодом)." этого я не понял. Можно написать куда войти и что нажать?

2020-04-14 15:36 UTC, AGrishin63 commented on hw01_hello_now/main.go
> +	fmt.Println("current time:", time.Now().Format("2006-01-02 15:04:05 +0000 UTC"))
Вот, что я делаю, чтобы обновить исправления:
git commit -am "HW3 is completed" 
git push origin hw03_frequency_analysis
 Где я могу посмотреть обновился ли текст моих программ?

2020-04-14 15:49 UTC, AGrishin63 commented
Дублирую.Добрый день. В экземпляре на моём компьютере все замечания устранены. Я старался делать всё по инструкции, почему мой вариант не попал к вам и почему в PR 3 ДЗ я не знаю и не вижу трёх ДЗ. Кроме того я просил объяснить откуда надо отправлять преподавателю ссылки на PR? В инструкции сказано, что в личном кабинете OTUS есть ссылка на чат с преподавателем, я не нашёл этой ссылки. В личном кабинете OTUS в домашних заданиях 1 и 2 были ссылки, а в ДЗ 3 ссылок нет. Далее:"Скорее всего нужно подмержить в hw03_frequency_analysis мастер (не руками копировать-ставлять файлы с кодом)." этого я не понял. Можно написать куда войти и что нажать?   AGrishin63    11 minutes ago  Author   Owner Вот, что я делаю, чтобы обновить исправления:git commit -am "HW3 is completed"git push origin hw03_frequency_analysisГде я могу посмотреть обновился ли текст моих программ?12.04.2020, 19:30, "Anton Telyshev" <notifications@github.com>:
@Antonboom requested changes on this pull request.

Здравствуйте!
Вы написали , что убрали все лишнее, но в итоге в PR теперь 3 ДЗ вместо одного, а старые замечания не исправлены.
Давайте сделаем так, чтобы в PR было только одно ДЗ.
Скорее всего нужно подмержить в hw03_frequency_analysis мастер (не руками копировать-ставлять файлы с кодом).
Можете создать новый PR, если с этим тяжко.
Потом продолжим, спасибо!

In hw01_hello_now/main.go:
>  func main() {
-	// Place your code here
+	fmt.Println("current time:", time.Now().Format("2006-01-02 15:04:05 +0000 UTC"))

Как сюда попало 1 ДЗ?



In hw02_unpack_string/unpack.go:
> @@ -1,12 +1,30 @@
 package hw02_unpack_string //nolint:golint,stylecheck
 
-import (
-	"errors"
-)
-
+https://github.com/AGrishin63/griHW/compare/hw02_unpack_string?expand=1&template=hw02_unpack_string.md

Почему здесь 2 ДЗ?
И что за ссылка посреди кода - это не скомпилируется. Хотя бы комментарий



In hw03_frequency_analysis/top.go:
>  
-func Top10(_ string) []string {
+import (
+	"fmt"
+	//	"os"
+
+	s "strings"
+)
+
+// func main() {

Про неиспользуемый код я уже писал.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-04-15 06:14 UTC, Antonboom commented on hw01_hello_now/main.go
> +	fmt.Println("current time:", time.Now().Format("2006-01-02 15:04:05 +0000 UTC"))
Александр, как найти вас в Slack?

Не вижу вас в канале 2го потока #go-2020-02.
Вы можете написать мне в личку?

2020-04-24 06:29 UTC, Antonboom requested changes
https://otus.ru/teacher-lk/homework/79863/6027/

Здравствуйте!

1) Вы проигнорировали использование шаблона при создании PR (&template=hw03_frequency_analysis.md) :(

2) Хорошее решение, но местами сложное и есть ряд косметических замечаний. Хотелось бы по максимуму использовать средства языка, которые он нам предоставляет

3) Новые юнит-тесты не написаны.

Как видно из критериев к ДЗ, я не могу его принять.
4 / 10

2020-04-24 06:29 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	var topVal []int = make([]int, 0, top)
Go умеет определять типы переменных во время компиляции, следует писать
```
topVal := make([]int, 0, top)
```
это гораздо короче и для этого оператор `:=` и создан

2020-04-24 06:29 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	for j := 0; j < len(words); j++ {
Вам бы добавить ньюлайнов между логически-выделенными блоками кода, сложно читать

2020-04-24 06:29 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +			v := dict[word]
достаточно написать
```golang
dict[word]++
```

2020-04-24 06:29 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +	} //for
```
// for
```
подобного рода комментарии используются, когда блок не помещается на экран. 
в двустрочных блоках кода это излишне

2020-04-24 06:29 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +			for i = 0; i < len(topVal); i++ {
что за страсти. такие вещи сложно понимать и поддерживать вашим коллегам.

как вы смотрите на то, чтобы собрать слайс структурок, отсортировать его методом стандартной библиотекой и вытащить оттуда top?

2020-05-05 06:19 UTC, AGrishin63 commented on hw03_frequency_analysis/top.go
> +			for i = 0; i < len(topVal); i++ {
Добрый, день Антон. Поправил задачу по вашим замечаниям и добавил проверку, но мне казалось, что преложенный мной метод был более эффективен, т.к. не было необходимости сортировать слайс структур целиком, он ведь мог бы быть размером в несколько тысяч. Я попробовал проверить оба варианта на большом массиве, но к удивлению обнаружил, что время выполнения примерно одинаково. Не могли бы вы объяснить почему?

2020-05-05 16:26 UTC, Antonboom commented on hw03_frequency_analysis/top.go
> +			for i = 0; i < len(topVal); i++ {
Вы запушили новую версию?
Не вижу изменений по своим замечаниям

2020-06-12 09:25 UTC, Antonboom commented
@AGrishin63 
Вы запушили новую версию?
Не вижу изменений по своим замечаниям

Вы сделали это не в ту ветку?

2020-06-12 09:50 UTC, Antonboom approved these changes
Принято

10 / 10

2020-06-12 09:52 UTC, AGrishin63 commented
3 ДЗ запушил, а 4 выдаё1т ошибку 12.06.2020, 12:25, "Anton Telyshev" <notifications@github.com>: @AGrishin63Вы запушили новую версию?Не вижу изменений по своим замечаниямВы сделали это не в ту ветку?—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

2020-06-12 09:53 UTC, merged

2020-06-12 09:53 UTC, Antonboom commented
@AGrishin63, замержил, чтобы было меньше проблем при работе с hw04

По hw04 отписал в его PR